# We perform a simple analysis of the submissions, metadata provided, and generate a filtered list of valid submissions

## Read metadata and filter content

Load the metadata file and set the submission id as index.

In [1]:
import pandas as pd
from icdar_maptext_analysis.submissions_metadata import SUBMISSION_METADATA
len(SUBMISSION_METADATA)

35

This is consistent with the number of submissions listed in the platform for the competition.

In [2]:
SUBMISSION_METADATA

Unnamed: 0        User                 Date  Challenge  Task  Valid  \
ID                                                                            
121832        2128      user_9  2025-01-09 21:26:52         32     1      1   
121864        2131      user_9  2025-01-10 15:59:12         32     2      1   
121874        2133      user_9  2025-01-10 21:22:43         32     3      1   
121875        2134      user_9  2025-01-10 21:47:55         32     3      1   
121876        2135      user_9  2025-01-10 21:48:53         32     3      1   
121877        2136      user_9  2025-01-10 21:54:07         32     3      1   
121878        2137      user_9  2025-01-10 21:54:15         32     3      1   
121883        2140      user_9  2025-01-10 22:47:44         32     4      1   
124853        2167  user_61902  2025-03-27 05:42:44         32     1      1   
124854        2168  user_61902  2025-03-27 07:17:51         32     1      1   
124855        2169  user_61902  2025-03-27 07:21:00         32     2      1   
124937        2174  user_51978  2025-03-28 15:21:20         32     4      1   
124938        2175  user_51978  2025-03-28 15:32:09         32     2      1   
124939        2176  user_51978  2025-03-28 15:37:32         32     3      1   
124940        2177  user_51978  2025-03-28 15:41:49         32     1      1   
124983        2181  user_51343  2025-03-31 05:59:25         32     1      1   
124984        2182  user_51343  2025-03-31 06:39:32         32     2      1   
124985        2183  user_51343  2025-03-31 06:42:15         32     3      1   
124986        2184  user_51343  2025-03-31 06:47:57         32     4      1   
124987        2185  user_51343  2025-03-31 06:48:22         32     4      1   
125336        2230   user_4637  2025-04-13 18:12:17         32     4      1   
125454        2249   user_4637  2025-04-19 11:04:33         32     3      1   
125455        2250   user_4637  2025-04-19 11:06:24         32     2      1   
125456        2251   user_4637  2025-04-19 11:11:22         32     1      1   
125458        2252  user_59938  2025-04-19 12:00:13         32     1      1   
125460        2254  user_59938  2025-04-19 15:37:59         32     2      1   
125463        2257  user_59938  2025-04-19 15:54:09         32     3      1   
125465        2259  user_59938  2025-04-19 15:59:19         32     4      1   
125479        2263  user_60141  2025-04-20 15:37:26         32     1      1   
125480        2264  user_51696  2025-04-20 15:59:46         32     3      1   
125481        2265  user_51696  2025-04-20 16:04:17         32     1      1   
125646        2296      user_9  2025-04-29 17:44:34         32     1      1   
125647        2297      user_9  2025-04-29 17:48:56         32     2      1   
125648        2298      user_9  2025-04-29 17:57:42         32     3      1   
125651        2299      user_9  2025-04-29 18:07:22         32     4      1   

        Competition  Val. Set  \
ID                              
121832            1         0   
121864            1         0   
121874            1         0   
121875            1         0   
121876            1         0   
121877            1         0   
121878            1         0   
121883            1         0   
124853            1         0   
124854            1         0   
124855            1         0   
124937            1         0   
124938            1         0   
124939            1         0   
124940            1         0   
124983            1         0   
124984            1         0   
124985            1         0   
124986            1         0   
124987            1         0   
125336            1         0   
125454            1         0   
125455            1         0   
125456            1         0   
125458            1         0   
125460            1         0   
125463            1         0   
125465            1         0   
125479            1         0   
125480            1         0   
125481            1         

Based on a manual check, it looks like the following submissions (probably preliminary tests from participants) can be deleted from our analysis:
TASK1
- 124854 for t1/f1 ("MapTextSpotter" zero perf)
- 125481 for t1/f2 ("Word-Level Text Detection..." zero perf) ← warning has valid content for t1/f1

TASK2
- 124855 for t2/f1 ("MapTextSpotter", almost zero perf) ← really remove?
- 125460 for t2/f1,f2,f3 ("YOLOv8_ViTAE_PolygonDetector", zero perf)
- 124984 for t2/f1,f3 ("MapText Strong Pipeline", zero perf)

TASK3
- 125480 for t3/f2 ("Word-Level Text Detection", zero perf) ← warning has valid content for t3/f1

TASK4
- 125465 for t4/f1,f2 ("YOLOv8_ViTAE_PolygonDetector", zero perf)
- 124986 for t4/f1 ("MapText Strong Pipeline", zero perf)
- 124987 for t4/f1 ("MapText Strong Pipeline", zero perf)

In [3]:
from dataclasses import dataclass

@dataclass
class SubmissionTaskSubset:
    submission_id: int
    task_id: int
    subset_id: int

# The following list contains the submission IDs, task IDs, and subset IDs of the submissions to be deleted for the 2025 competition.
submissions_to_delete: list[SubmissionTaskSubset] = [
    SubmissionTaskSubset(124854, 1, 1),
    SubmissionTaskSubset(125481, 1, 2),
    
    SubmissionTaskSubset(124855, 2, 1),
    SubmissionTaskSubset(124984, 2, 1),
    SubmissionTaskSubset(124984, 2, 3),  # not exported anyway
    SubmissionTaskSubset(125460, 2, 1),
    SubmissionTaskSubset(125460, 2, 2),
    SubmissionTaskSubset(125460, 2, 3),  # not exported anyway

    SubmissionTaskSubset(125480, 3, 2),

    SubmissionTaskSubset(124986, 4, 1),
    SubmissionTaskSubset(124987, 4, 1),
    SubmissionTaskSubset(125465, 4, 1),
    SubmissionTaskSubset(125465, 4, 2),
]
    

Collect the set of submission ids for which evaluation is available.

In [4]:
from icdar_maptext_analysis.loaders import VALID_SUBSETS, VALID_TASKS, list_evaluations
available_evaluations = []
for task_id in VALID_TASKS:
    for subset in VALID_SUBSETS:
        available_evaluations.extend(list_evaluations(task_id, subset))
available_evaluations = set(int(x) for x in available_evaluations)
len(available_evaluations)

35

In [5]:
# These are the ids of the submissions that are on the platform (for the 2025 competition)
# Gathered from <https://rrc.cvc.uab.es/?ch=32&com=all_methods>, using the filter "Competition=Yes"
submissions_ids_platform = {
    121832, 121864, 121874, 121875, 121876, 121877, 121878, 121883, 124853, 124854, 124855,
    124937, 124938, 124939, 124940, 124983, 124984, 124985, 124986, 124987, 125336, 125454,
    125455, 125456, 125458, 125460, 125463, 125465, 125479, 125480, 125481, 125646, 125647,
    125648, 125651,
}

In [6]:
# Do we have evaluations for all the submissions from the platform?
if available_evaluations != submissions_ids_platform:
    print("The set of evaluations is not consistent with the submissions on the platform")
    missing_evaluations = submissions_ids_platform - available_evaluations
    if missing_evaluations:
        print("We are missing evaluations for the following submissions from the platform:")
        for submission in missing_evaluations:
            print(f"- {submission}")
    else:
        print("No missing evaluations")
    extra_evaluations = available_evaluations - submissions_ids_platform
    if extra_evaluations:
        print("We have extra evaluations for submissions which are not on the platform:")
        for submission in extra_evaluations:
            print(f"- {submission}")
    else:
        print("No extra evaluations")
    raise ValueError("The set of evaluations is not consistent with the submissions on the platform. Please fix this before proceeding.")
else:
    print("We have evaluations for all the submissions from the platform.")


We have evaluations for all the submissions from the platform.


### Check for multiple submissions for each task

In [7]:
# count the number of submissions per user for each task
SUBMISSION_METADATA.groupby(["User", "Task"]).size().unstack().fillna(0).astype(int)

Task        1  2  3  4
User                  
user_4637   1  1  1  1
user_51343  1  1  1  2
user_51696  1  0  1  0
user_51978  1  1  1  1
user_59938  1  1  1  1
user_60141  1  0  0  0
user_61902  2  1  0  0
user_9      2  2  6  2

In [8]:
SUBMISSION_METADATA[(SUBMISSION_METADATA["User"] == "user_61902") & (SUBMISSION_METADATA["Task"] == 1) ]

Unnamed: 0        User                 Date  Challenge  Task  Valid  \
ID                                                                            
124853        2167  user_61902  2025-03-27 05:42:44         32     1      1   
124854        2168  user_61902  2025-03-27 07:17:51         32     1      1   

        Competition  Val. Set           Title  Filesize  Public Eval.time  \
ID                                                                          
124853            1         0  MapTextSpotter  13984721       1  00:04:57   
124854            1         0  MapTextSpotter  99588219       1  00:06:52   

        Results size  
ID                    
124853         425.0  
124854         333.0

We properly deleted the invalid submissions 124854 and 124855 with zero scores.

In [9]:
SUBMISSION_METADATA[(SUBMISSION_METADATA["User"] == "user_51343") & (SUBMISSION_METADATA["Task"] == 4) ]

Unnamed: 0        User                 Date  Challenge  Task  Valid  \
ID                                                                            
124986        2184  user_51343  2025-03-31 06:47:57         32     4      1   
124987        2185  user_51343  2025-03-31 06:48:22         32     4      1   

        Competition  Val. Set                    Title   Filesize  Public  \
ID                                                                          
124986            1         0  MapText Strong Pipeline  160571002       1   
124987            1         0  MapText Strong Pipeline  160571002       1   

       Eval.time  Results size  
ID                              
124986  00:42:57         545.0  
124987  01:02:38         545.0

We properly deleted these two invalid submissions with zero scores.

`user_9` are the organizers, they posted the baselines. This is fine.

## Some participation statistics for the 2025 edition
(based on manual counts on the platform)

We have 7 participating teams in the competition.
They made a total of 24 valid submissions for each task-dataset challenge (over all the 10 possible task-dataset open challenges).

The organizers also contributed baselines for all tasks and datasets: 8 from the previous edition, and 10 new ones.

This leaves us with a total of 42 single submissions (task-dataset) to analyze in theory.

## Create a clean list of valid submissions per task per subset

We found several duplicate and test submissions, and a participant apparently submitted the same file for two methods for task 1, IGN subset.

We produce here clean list we can refer to in later stages of the analysis.

In [10]:
from icdar_maptext_analysis.loaders import list_submissions, VALID_TASKS, VALID_SUBSETS, DATASET_NAMETOID
from icdar_maptext_analysis.submissions_metadata import lookup_generate_title
from typing import List, Dict, Union
import pandas as pd

In [11]:
@dataclass
class ValidSubmissionRecord:
    task: int
    subset: int
    submission_id: int
    method_name: str

valid_submissions: list[ValidSubmissionRecord] = []
dropped_count = 0
for task_id in VALID_TASKS:
    for subset in VALID_SUBSETS:
        for submission_id in list_submissions(task_id, subset):
            submission_id = int(submission_id)
            subset_id = DATASET_NAMETOID[subset]
            sub_data = SubmissionTaskSubset(submission_id, task_id, subset_id)
            sub_title = lookup_generate_title(submission_id)
            # Check if the submission is in the list of submissions to delete
            if sub_data in submissions_to_delete:
                print(f"Skipping submission {submission_id} ({sub_title}) for t{task_id}/{subset} (manually deleted)")
                dropped_count += 1
                continue
            # Check if the submission is in the list of available evaluations
            available_evaluations = [int(x) for x in list_evaluations(task_id, subset)]
            if submission_id not in available_evaluations:
                print(f"!!! Skipping submission {submission_id} ({sub_title}) for t{task_id}/{subset} (no evaluation available)")
                dropped_count += 1
                continue
            record = ValidSubmissionRecord(
                task_id,
                subset,
                submission_id,
                sub_title,
            )
            valid_submissions.append(record)
print(f"Dropped {dropped_count} submissions")
print(f"Kept {len(valid_submissions)} submissions")
valid_submissions = pd.DataFrame(valid_submissions)
valid_submissions.sample(5, random_state=0)

Skipping submission 124854 (MapTextSpotter) for t1/rumsey (manually deleted)
Skipping submission 125481 (Word-Level Text Detection on Historical Maps Using Multi-Stage Preprocessing and PaddleOCR) for t1/ign (manually deleted)
Skipping submission 124855 (MapTextSpotter) for t2/rumsey (manually deleted)
Skipping submission 124984 (MapText Strong Pipeline) for t2/rumsey (manually deleted)
Skipping submission 125460 (YOLOv8_ViTAE_PolygonDetector) for t2/rumsey (manually deleted)
Skipping submission 125460 (YOLOv8_ViTAE_PolygonDetector) for t2/ign (manually deleted)
Skipping submission 125480 (Word-Level Text Detection and Recognition on Historical Maps Using Preprocessing and PaddleOCR) for t3/ign (manually deleted)
Skipping submission 124986 (MapText Strong Pipeline) for t4/rumsey (manually deleted)
Skipping submission 124987 (MapText Strong Pipeline) for t4/rumsey (manually deleted)
Skipping submission 125465 (YOLOv8_ViTAE_PolygonDetector) for t4/rumsey (manually deleted)
Skipping submi

task  subset  submission_id  \
30     3  rumsey         125480   
36     3     twh         125648   
27     3  rumsey         124985   
4      1  rumsey         125456   
10     1     ign         125479   

                                          method_name  
30  Word-Level Text Detection and Recognition on H...  
36                           Baseline TESTR Finetuned  
27                            MapText Strong Pipeline  
4                                 CREPE + BezierCurve  
10                                         PolyTextTR

In [12]:
valid_submissions.to_csv("valid_submissions.csv", index=False)

In [13]:
# test re-loading
valid_submissions = pd.read_csv("valid_submissions.csv")
valid_submissions.sample(5, random_state=0)

task  subset  submission_id  \
30     3  rumsey         125480   
36     3     twh         125648   
27     3  rumsey         124985   
4      1  rumsey         125456   
10     1     ign         125479   

                                          method_name  
30  Word-Level Text Detection and Recognition on H...  
36                           Baseline TESTR Finetuned  
27                            MapText Strong Pipeline  
4                                 CREPE + BezierCurve  
10                                         PolyTextTR

OK. Ready to continue.